// This file is part of the REMOTE API
// 
// Copyright 2006-2013 Dr. Marc Andreas Freese. All rights reserved. 
// marc@coppeliarobotics.com
// www.coppeliarobotics.com
// 
// The REMOTE API is licensed under the terms of GNU GPL:
// 
// -------------------------------------------------------------------
// The REMOTE API is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// The REMOTE API is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with the REMOTE API.  If not, see <http://www.gnu.org/licenses/>.
// -------------------------------------------------------------------
//
// This file was automatically created for V-REP release V3.0.1 on January 20th 2013

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class remoteApi */

#ifdef __cplusplus
extern "C" {
#endif
#undef remoteApi_SIMX_HEADER_SIZE
#define remoteApi_SIMX_HEADER_SIZE 18L
#undef remoteApi_simx_headeroffset_crc
#define remoteApi_simx_headeroffset_crc 0L
#undef remoteApi_simx_headeroffset_version
#define remoteApi_simx_headeroffset_version 2L
#undef remoteApi_simx_headeroffset_message_id
#define remoteApi_simx_headeroffset_message_id 3L
#undef remoteApi_simx_headeroffset_client_time
#define remoteApi_simx_headeroffset_client_time 7L
#undef remoteApi_simx_headeroffset_server_time
#define remoteApi_simx_headeroffset_server_time 11L
#undef remoteApi_simx_headeroffset_scene_id
#define remoteApi_simx_headeroffset_scene_id 15L
#undef remoteApi_simx_headeroffset_server_state
#define remoteApi_simx_headeroffset_server_state 17L
#undef remoteApi_SIMX_SUBHEADER_SIZE
#define remoteApi_SIMX_SUBHEADER_SIZE 26L
#undef remoteApi_simx_cmdheaderoffset_mem_size
#define remoteApi_simx_cmdheaderoffset_mem_size 0L
#undef remoteApi_simx_cmdheaderoffset_full_mem_size
#define remoteApi_simx_cmdheaderoffset_full_mem_size 4L
#undef remoteApi_simx_cmdheaderoffset_pdata_offset0
#define remoteApi_simx_cmdheaderoffset_pdata_offset0 8L
#undef remoteApi_simx_cmdheaderoffset_pdata_offset1
#define remoteApi_simx_cmdheaderoffset_pdata_offset1 10L
#undef remoteApi_simx_cmdheaderoffset_cmd
#define remoteApi_simx_cmdheaderoffset_cmd 14L
#undef remoteApi_simx_cmdheaderoffset_delay_or_split
#define remoteApi_simx_cmdheaderoffset_delay_or_split 18L
#undef remoteApi_simx_cmdheaderoffset_sim_time
#define remoteApi_simx_cmdheaderoffset_sim_time 20L
#undef remoteApi_simx_cmdheaderoffset_status
#define remoteApi_simx_cmdheaderoffset_status 24L
#undef remoteApi_simx_cmdheaderoffset_reserved
#define remoteApi_simx_cmdheaderoffset_reserved 25L
#undef remoteApi_sim_object_shape_type
#define remoteApi_sim_object_shape_type 0L
#undef remoteApi_sim_object_joint_type
#define remoteApi_sim_object_joint_type 1L
#undef remoteApi_sim_object_graph_type
#define remoteApi_sim_object_graph_type 2L
#undef remoteApi_sim_object_camera_type
#define remoteApi_sim_object_camera_type 3L
#undef remoteApi_sim_object_dummy_type
#define remoteApi_sim_object_dummy_type 4L
#undef remoteApi_sim_object_proximitysensor_type
#define remoteApi_sim_object_proximitysensor_type 5L
#undef remoteApi_sim_object_reserved1
#define remoteApi_sim_object_reserved1 6L
#undef remoteApi_sim_object_reserved2
#define remoteApi_sim_object_reserved2 7L
#undef remoteApi_sim_object_path_type
#define remoteApi_sim_object_path_type 8L
#undef remoteApi_sim_object_visionsensor_type
#define remoteApi_sim_object_visionsensor_type 9L
#undef remoteApi_sim_object_volume_type
#define remoteApi_sim_object_volume_type 10L
#undef remoteApi_sim_object_mill_type
#define remoteApi_sim_object_mill_type 11L
#undef remoteApi_sim_object_forcesensor_type
#define remoteApi_sim_object_forcesensor_type 12L
#undef remoteApi_sim_object_light_type
#define remoteApi_sim_object_light_type 13L
#undef remoteApi_sim_object_mirror_type
#define remoteApi_sim_object_mirror_type 14L
#undef remoteApi_sim_object_type_end
#define remoteApi_sim_object_type_end 108L
#undef remoteApi_sim_appobj_object_type
#define remoteApi_sim_appobj_object_type 109L
#undef remoteApi_sim_appobj_collision_type
#define remoteApi_sim_appobj_collision_type 110L
#undef remoteApi_sim_appobj_distance_type
#define remoteApi_sim_appobj_distance_type 111L
#undef remoteApi_sim_appobj_simulation_type
#define remoteApi_sim_appobj_simulation_type 112L
#undef remoteApi_sim_appobj_ik_type
#define remoteApi_sim_appobj_ik_type 113L
#undef remoteApi_sim_appobj_constraintsolver_type
#define remoteApi_sim_appobj_constraintsolver_type 114L
#undef remoteApi_sim_appobj_collection_type
#define remoteApi_sim_appobj_collection_type 115L
#undef remoteApi_sim_appobj_ui_type
#define remoteApi_sim_appobj_ui_type 116L
#undef remoteApi_sim_appobj_script_type
#define remoteApi_sim_appobj_script_type 117L
#undef remoteApi_sim_appobj_pathplanning_type
#define remoteApi_sim_appobj_pathplanning_type 118L
#undef remoteApi_sim_appobj_RESERVED_type
#define remoteApi_sim_appobj_RESERVED_type 119L
#undef remoteApi_sim_appobj_texture_type
#define remoteApi_sim_appobj_texture_type 120L
#undef remoteApi_sim_ik_pseudo_inverse_method
#define remoteApi_sim_ik_pseudo_inverse_method 0L
#undef remoteApi_sim_ik_damped_least_squares_method
#define remoteApi_sim_ik_damped_least_squares_method 1L
#undef remoteApi_sim_ik_jacobian_transpose_method
#define remoteApi_sim_ik_jacobian_transpose_method 2L
#undef remoteApi_sim_ik_x_constraint
#define remoteApi_sim_ik_x_constraint 1L
#undef remoteApi_sim_ik_y_constraint
#define remoteApi_sim_ik_y_constraint 2L
#undef remoteApi_sim_ik_z_constraint
#define remoteApi_sim_ik_z_constraint 4L
#undef remoteApi_sim_ik_alpha_beta_constraint
#define remoteApi_sim_ik_alpha_beta_constraint 8L
#undef remoteApi_sim_ik_gamma_constraint
#define remoteApi_sim_ik_gamma_constraint 16L
#undef remoteApi_sim_ik_avoidance_constraint
#define remoteApi_sim_ik_avoidance_constraint 64L
#undef remoteApi_sim_ikresult_not_performed
#define remoteApi_sim_ikresult_not_performed 0L
#undef remoteApi_sim_ikresult_success
#define remoteApi_sim_ikresult_success 1L
#undef remoteApi_sim_ikresult_fail
#define remoteApi_sim_ikresult_fail 2L
#undef remoteApi_sim_light_omnidirectional_subtype
#define remoteApi_sim_light_omnidirectional_subtype 1L
#undef remoteApi_sim_light_spot_subtype
#define remoteApi_sim_light_spot_subtype 2L
#undef remoteApi_sim_light_directional_subtype
#define remoteApi_sim_light_directional_subtype 3L
#undef remoteApi_sim_joint_revolute_subtype
#define remoteApi_sim_joint_revolute_subtype 10L
#undef remoteApi_sim_joint_prismatic_subtype
#define remoteApi_sim_joint_prismatic_subtype 11L
#undef remoteApi_sim_joint_spherical_subtype
#define remoteApi_sim_joint_spherical_subtype 12L
#undef remoteApi_sim_shape_simpleshape_subtype
#define remoteApi_sim_shape_simpleshape_subtype 20L
#undef remoteApi_sim_shape_multishape_subtype
#define remoteApi_sim_shape_multishape_subtype 21L
#undef remoteApi_sim_proximitysensor_pyramid_subtype
#define remoteApi_sim_proximitysensor_pyramid_subtype 30L
#undef remoteApi_sim_proximitysensor_cylinder_subtype
#define remoteApi_sim_proximitysensor_cylinder_subtype 31L
#undef remoteApi_sim_proximitysensor_disc_subtype
#define remoteApi_sim_proximitysensor_disc_subtype 32L
#undef remoteApi_sim_proximitysensor_cone_subtype
#define remoteApi_sim_proximitysensor_cone_subtype 33L
#undef remoteApi_sim_proximitysensor_ray_subtype
#define remoteApi_sim_proximitysensor_ray_subtype 34L
#undef remoteApi_sim_mill_pyramid_subtype
#define remoteApi_sim_mill_pyramid_subtype 40L
#undef remoteApi_sim_mill_cylinder_subtype
#define remoteApi_sim_mill_cylinder_subtype 41L
#undef remoteApi_sim_mill_disc_subtype
#define remoteApi_sim_mill_disc_subtype 42L
#undef remoteApi_sim_mill_cone_subtype
#define remoteApi_sim_mill_cone_subtype 43L
#undef remoteApi_sim_object_no_subtype
#define remoteApi_sim_object_no_subtype 200L
#undef remoteApi_sim_objectspecialproperty_collidable
#define remoteApi_sim_objectspecialproperty_collidable 1L
#undef remoteApi_sim_objectspecialproperty_measurable
#define remoteApi_sim_objectspecialproperty_measurable 2L
#undef remoteApi_sim_objectspecialproperty_detectable_ultrasonic
#define remoteApi_sim_objectspecialproperty_detectable_ultrasonic 16L
#undef remoteApi_sim_objectspecialproperty_detectable_infrared
#define remoteApi_sim_objectspecialproperty_detectable_infrared 32L
#undef remoteApi_sim_objectspecialproperty_detectable_laser
#define remoteApi_sim_objectspecialproperty_detectable_laser 64L
#undef remoteApi_sim_objectspecialproperty_detectable_inductive
#define remoteApi_sim_objectspecialproperty_detectable_inductive 128L
#undef remoteApi_sim_objectspecialproperty_detectable_capacitive
#define remoteApi_sim_objectspecialproperty_detectable_capacitive 256L
#undef remoteApi_sim_objectspecialproperty_renderable
#define remoteApi_sim_objectspecialproperty_renderable 512L
#undef remoteApi_sim_objectspecialproperty_detectable_all
#define remoteApi_sim_objectspecialproperty_detectable_all 496L
#undef remoteApi_sim_objectspecialproperty_cuttable
#define remoteApi_sim_objectspecialproperty_cuttable 1024L
#undef remoteApi_sim_objectspecialproperty_pathplanning_ignored
#define remoteApi_sim_objectspecialproperty_pathplanning_ignored 2048L
#undef remoteApi_sim_modelproperty_not_collidable
#define remoteApi_sim_modelproperty_not_collidable 1L
#undef remoteApi_sim_modelproperty_not_measurable
#define remoteApi_sim_modelproperty_not_measurable 2L
#undef remoteApi_sim_modelproperty_not_renderable
#define remoteApi_sim_modelproperty_not_renderable 4L
#undef remoteApi_sim_modelproperty_not_detectable
#define remoteApi_sim_modelproperty_not_detectable 8L
#undef remoteApi_sim_modelproperty_not_cuttable
#define remoteApi_sim_modelproperty_not_cuttable 16L
#undef remoteApi_sim_modelproperty_not_dynamic
#define remoteApi_sim_modelproperty_not_dynamic 32L
#undef remoteApi_sim_modelproperty_not_respondable
#define remoteApi_sim_modelproperty_not_respondable 64L
#undef remoteApi_sim_modelproperty_not_reset
#define remoteApi_sim_modelproperty_not_reset 128L
#undef remoteApi_sim_modelproperty_not_visible
#define remoteApi_sim_modelproperty_not_visible 256L
#undef remoteApi_sim_modelproperty_not_model
#define remoteApi_sim_modelproperty_not_model 61440L
#undef remoteApi_sim_message_ui_button_state_change
#define remoteApi_sim_message_ui_button_state_change 0L
#undef remoteApi_sim_message_reserved9
#define remoteApi_sim_message_reserved9 1L
#undef remoteApi_sim_message_object_selection_changed
#define remoteApi_sim_message_object_selection_changed 2L
#undef remoteApi_im_message_reserved10
#define remoteApi_im_message_reserved10 3L
#undef remoteApi_sim_message_model_loaded
#define remoteApi_sim_message_model_loaded 4L
#undef remoteApi_sim_message_reserved11
#define remoteApi_sim_message_reserved11 5L
#undef remoteApi_sim_message_keypress
#define remoteApi_sim_message_keypress 6L
#undef remoteApi_sim_message_bannerclicked
#define remoteApi_sim_message_bannerclicked 7L
#undef remoteApi_sim_message_for_c_api_only_start
#define remoteApi_sim_message_for_c_api_only_start 256L
#undef remoteApi_sim_message_reserved1
#define remoteApi_sim_message_reserved1 257L
#undef remoteApi_sim_message_reserved2
#define remoteApi_sim_message_reserved2 258L
#undef remoteApi_sim_message_reserved3
#define remoteApi_sim_message_reserved3 259L
#undef remoteApi_sim_message_eventcallback_scenesave
#define remoteApi_sim_message_eventcallback_scenesave 260L
#undef remoteApi_sim_message_eventcallback_modelsave
#define remoteApi_sim_message_eventcallback_modelsave 261L
#undef remoteApi_sim_message_eventcallback_moduleopen
#define remoteApi_sim_message_eventcallback_moduleopen 262L
#undef remoteApi_sim_message_eventcallback_modulehandle
#define remoteApi_sim_message_eventcallback_modulehandle 263L
#undef remoteApi_sim_message_eventcallback_moduleclose
#define remoteApi_sim_message_eventcallback_moduleclose 264L
#undef remoteApi_sim_message_reserved4
#define remoteApi_sim_message_reserved4 265L
#undef remoteApi_sim_message_reserved5
#define remoteApi_sim_message_reserved5 266L
#undef remoteApi_sim_message_reserved6
#define remoteApi_sim_message_reserved6 267L
#undef remoteApi_sim_message_reserved7
#define remoteApi_sim_message_reserved7 268L
#undef remoteApi_sim_message_eventcallback_instancepass
#define remoteApi_sim_message_eventcallback_instancepass 269L
#undef remoteApi_sim_message_eventcallback_broadcast
#define remoteApi_sim_message_eventcallback_broadcast 270L
#undef remoteApi_sim_message_eventcallback_imagefilter_enumreset
#define remoteApi_sim_message_eventcallback_imagefilter_enumreset 271L
#undef remoteApi_sim_message_eventcallback_imagefilter_enumerate
#define remoteApi_sim_message_eventcallback_imagefilter_enumerate 272L
#undef remoteApi_sim_message_eventcallback_imagefilter_adjustparams
#define remoteApi_sim_message_eventcallback_imagefilter_adjustparams 273L
#undef remoteApi_sim_message_eventcallback_imagefilter_reserved
#define remoteApi_sim_message_eventcallback_imagefilter_reserved 274L
#undef remoteApi_sim_message_eventcallback_imagefilter_process
#define remoteApi_sim_message_eventcallback_imagefilter_process 275L
#undef remoteApi_sim_message_eventcallback_reserved1
#define remoteApi_sim_message_eventcallback_reserved1 276L
#undef remoteApi_sim_message_eventcallback_reserved2
#define remoteApi_sim_message_eventcallback_reserved2 277L
#undef remoteApi_sim_message_eventcallback_reserved3
#define remoteApi_sim_message_eventcallback_reserved3 278L
#undef remoteApi_sim_message_eventcallback_reserved4
#define remoteApi_sim_message_eventcallback_reserved4 279L
#undef remoteApi_sim_message_eventcallback_abouttoundo
#define remoteApi_sim_message_eventcallback_abouttoundo 280L
#undef remoteApi_sim_message_eventcallback_undoperformed
#define remoteApi_sim_message_eventcallback_undoperformed 281L
#undef remoteApi_sim_message_eventcallback_abouttoredo
#define remoteApi_sim_message_eventcallback_abouttoredo 282L
#undef remoteApi_sim_message_eventcallback_redoperformed
#define remoteApi_sim_message_eventcallback_redoperformed 283L
#undef remoteApi_sim_message_eventcallback_scripticondblclick
#define remoteApi_sim_message_eventcallback_scripticondblclick 284L
#undef remoteApi_sim_message_eventcallback_simulationabouttostart
#define remoteApi_sim_message_eventcallback_simulationabouttostart 285L
#undef remoteApi_sim_message_eventcallback_simulationended
#define remoteApi_sim_message_eventcallback_simulationended 286L
#undef remoteApi_sim_message_eventcallback_reserved5
#define remoteApi_sim_message_eventcallback_reserved5 287L
#undef remoteApi_sim_message_eventcallback_keypress
#define remoteApi_sim_message_eventcallback_keypress 288L
#undef remoteApi_sim_message_eventcallback_modulehandleinsensingpart
#define remoteApi_sim_message_eventcallback_modulehandleinsensingpart 289L
#undef remoteApi_sim_message_eventcallback_renderingpass
#define remoteApi_sim_message_eventcallback_renderingpass 290L
#undef remoteApi_sim_message_eventcallback_bannerclicked
#define remoteApi_sim_message_eventcallback_bannerclicked 291L
#undef remoteApi_sim_message_eventcallback_menuitemselected
#define remoteApi_sim_message_eventcallback_menuitemselected 292L
#undef remoteApi_sim_message_eventcallback_refreshdialogs
#define remoteApi_sim_message_eventcallback_refreshdialogs 293L
#undef remoteApi_sim_message_eventcallback_sceneloaded
#define remoteApi_sim_message_eventcallback_sceneloaded 294L
#undef remoteApi_sim_message_eventcallback_modelloaded
#define remoteApi_sim_message_eventcallback_modelloaded 295L
#undef remoteApi_sim_message_eventcallback_instanceswitch
#define remoteApi_sim_message_eventcallback_instanceswitch 296L
#undef remoteApi_sim_message_eventcallback_guipass
#define remoteApi_sim_message_eventcallback_guipass 297L
#undef remoteApi_sim_message_eventcallback_mainscriptabouttobecalled
#define remoteApi_sim_message_eventcallback_mainscriptabouttobecalled 298L
#undef remoteApi_sim_message_simulation_start_resume_request
#define remoteApi_sim_message_simulation_start_resume_request 4096L
#undef remoteApi_sim_message_simulation_pause_request
#define remoteApi_sim_message_simulation_pause_request 4097L
#undef remoteApi_sim_message_simulation_stop_request
#define remoteApi_sim_message_simulation_stop_request 4098L
#undef remoteApi_sim_objectproperty_reserved1
#define remoteApi_sim_objectproperty_reserved1 0L
#undef remoteApi_sim_objectproperty_reserved2
#define remoteApi_sim_objectproperty_reserved2 1L
#undef remoteApi_sim_objectproperty_reserved3
#define remoteApi_sim_objectproperty_reserved3 2L
#undef remoteApi_sim_objectproperty_reserved4
#define remoteApi_sim_objectproperty_reserved4 3L
#undef remoteApi_sim_objectproperty_reserved5
#define remoteApi_sim_objectproperty_reserved5 4L
#undef remoteApi_sim_objectproperty_reserved6
#define remoteApi_sim_objectproperty_reserved6 8L
#undef remoteApi_sim_objectproperty_collapsed
#define remoteApi_sim_objectproperty_collapsed 16L
#undef remoteApi_sim_objectproperty_selectable
#define remoteApi_sim_objectproperty_selectable 32L
#undef remoteApi_sim_objectproperty_reserved7
#define remoteApi_sim_objectproperty_reserved7 64L
#undef remoteApi_sim_objectproperty_selectmodelbaseinstead
#define remoteApi_sim_objectproperty_selectmodelbaseinstead 128L
#undef remoteApi_sim_objectproperty_dontshowasinsidemodel
#define remoteApi_sim_objectproperty_dontshowasinsidemodel 256L
#undef remoteApi_sim_lua_arg_nil
#define remoteApi_sim_lua_arg_nil 0L
#undef remoteApi_sim_lua_arg_bool
#define remoteApi_sim_lua_arg_bool 1L
#undef remoteApi_sim_lua_arg_int
#define remoteApi_sim_lua_arg_int 2L
#undef remoteApi_sim_lua_arg_float
#define remoteApi_sim_lua_arg_float 3L
#undef remoteApi_sim_lua_arg_string
#define remoteApi_sim_lua_arg_string 4L
#undef remoteApi_sim_lua_arg_invalid
#define remoteApi_sim_lua_arg_invalid 5L
#undef remoteApi_sim_lua_arg_table
#define remoteApi_sim_lua_arg_table 8L
#undef remoteApi_sim_ui_property_visible
#define remoteApi_sim_ui_property_visible 1L
#undef remoteApi_sim_ui_property_visibleduringsimulationonly
#define remoteApi_sim_ui_property_visibleduringsimulationonly 2L
#undef remoteApi_sim_ui_property_moveable
#define remoteApi_sim_ui_property_moveable 4L
#undef remoteApi_sim_ui_property_relativetoleftborder
#define remoteApi_sim_ui_property_relativetoleftborder 8L
#undef remoteApi_sim_ui_property_relativetotopborder
#define remoteApi_sim_ui_property_relativetotopborder 256L
#undef remoteApi_sim_ui_property_fixedwidthfont
#define remoteApi_sim_ui_property_fixedwidthfont 32L
#undef remoteApi_sim_ui_property_systemblock
#define remoteApi_sim_ui_property_systemblock 64L
#undef remoteApi_sim_ui_property_settocenter
#define remoteApi_sim_ui_property_settocenter 128L
#undef remoteApi_sim_ui_property_rolledup
#define remoteApi_sim_ui_property_rolledup 256L
#undef remoteApi_sim_ui_property_selectassociatedobject
#define remoteApi_sim_ui_property_selectassociatedobject 512L
#undef remoteApi_sim_ui_property_visiblewhenobjectselected
#define remoteApi_sim_ui_property_visiblewhenobjectselected 1024L
#undef remoteApi_sim_buttonproperty_button
#define remoteApi_sim_buttonproperty_button 0L
#undef remoteApi_sim_buttonproperty_label
#define remoteApi_sim_buttonproperty_label 1L
#undef remoteApi_sim_buttonproperty_slider
#define remoteApi_sim_buttonproperty_slider 2L
#undef remoteApi_sim_buttonproperty_editbox
#define remoteApi_sim_buttonproperty_editbox 3L
#undef remoteApi_sim_buttonproperty_staydown
#define remoteApi_sim_buttonproperty_staydown 8L
#undef remoteApi_sim_buttonproperty_enabled
#define remoteApi_sim_buttonproperty_enabled 16L
#undef remoteApi_sim_buttonproperty_borderless
#define remoteApi_sim_buttonproperty_borderless 32L
#undef remoteApi_sim_buttonproperty_horizontallycentered
#define remoteApi_sim_buttonproperty_horizontallycentered 64L
#undef remoteApi_sim_buttonproperty_ignoremouse
#define remoteApi_sim_buttonproperty_ignoremouse 128L
#undef remoteApi_sim_buttonproperty_isdown
#define remoteApi_sim_buttonproperty_isdown 256L
#undef remoteApi_sim_buttonproperty_transparent
#define remoteApi_sim_buttonproperty_transparent 512L
#undef remoteApi_sim_buttonproperty_nobackgroundcolor
#define remoteApi_sim_buttonproperty_nobackgroundcolor 1024L
#undef remoteApi_sim_buttonproperty_rollupaction
#define remoteApi_sim_buttonproperty_rollupaction 2048L
#undef remoteApi_sim_buttonproperty_closeaction
#define remoteApi_sim_buttonproperty_closeaction 4096L
#undef remoteApi_sim_buttonproperty_verticallycentered
#define remoteApi_sim_buttonproperty_verticallycentered 8192L
#undef remoteApi_sim_buttonproperty_downupevent
#define remoteApi_sim_buttonproperty_downupevent 16384L
#undef remoteApi_sim_simulation_stopped
#define remoteApi_sim_simulation_stopped 0L
#undef remoteApi_sim_simulation_paused
#define remoteApi_sim_simulation_paused 8L
#undef remoteApi_sim_simulation_advancing
#define remoteApi_sim_simulation_advancing 16L
#undef remoteApi_sim_simulation_advancing_firstafterstop
#define remoteApi_sim_simulation_advancing_firstafterstop 16L
#undef remoteApi_sim_simulation_advancing_running
#define remoteApi_sim_simulation_advancing_running 17L
#undef remoteApi_sim_simulation_advancing_lastbeforepause
#define remoteApi_sim_simulation_advancing_lastbeforepause 19L
#undef remoteApi_sim_simulation_advancing_firstafterpause
#define remoteApi_sim_simulation_advancing_firstafterpause 20L
#undef remoteApi_sim_simulation_advancing_abouttostop
#define remoteApi_sim_simulation_advancing_abouttostop 21L
#undef remoteApi_sim_simulation_advancing_lastbeforestop
#define remoteApi_sim_simulation_advancing_lastbeforestop 22L
#undef remoteApi_sim_script_no_error
#define remoteApi_sim_script_no_error 0L
#undef remoteApi_sim_script_main_script_nonexistent
#define remoteApi_sim_script_main_script_nonexistent 1L
#undef remoteApi_sim_script_main_script_not_called
#define remoteApi_sim_script_main_script_not_called 2L
#undef remoteApi_sim_script_reentrance_error
#define remoteApi_sim_script_reentrance_error 4L
#undef remoteApi_sim_script_lua_error
#define remoteApi_sim_script_lua_error 8L
#undef remoteApi_sim_script_call_error
#define remoteApi_sim_script_call_error 16L
#undef remoteApi_sim_scripttype_mainscript
#define remoteApi_sim_scripttype_mainscript 0L
#undef remoteApi_sim_scripttype_childscript
#define remoteApi_sim_scripttype_childscript 1L
#undef remoteApi_sim_scripttype_pluginscript
#define remoteApi_sim_scripttype_pluginscript 2L
#undef remoteApi_sim_scripttype_threaded
#define remoteApi_sim_scripttype_threaded 240L
#undef remoteApi_sim_api_errormessage_ignore
#define remoteApi_sim_api_errormessage_ignore 0L
#undef remoteApi_sim_api_errormessage_report
#define remoteApi_sim_api_errormessage_report 1L
#undef remoteApi_sim_api_errormessage_output
#define remoteApi_sim_api_errormessage_output 2L
#undef remoteApi_sim_handle_all
#define remoteApi_sim_handle_all -2L
#undef remoteApi_sim_handle_all_except_explicit
#define remoteApi_sim_handle_all_except_explicit -3L
#undef remoteApi_sim_handle_self
#define remoteApi_sim_handle_self -4L
#undef remoteApi_sim_handle_main_script
#define remoteApi_sim_handle_main_script -5L
#undef remoteApi_sim_handle_tree
#define remoteApi_sim_handle_tree -6L
#undef remoteApi_sim_handle_chain
#define remoteApi_sim_handle_chain -7L
#undef remoteApi_sim_handle_single
#define remoteApi_sim_handle_single -8L
#undef remoteApi_sim_handle_default
#define remoteApi_sim_handle_default -9L
#undef remoteApi_sim_handle_all_except_self
#define remoteApi_sim_handle_all_except_self -10L
#undef remoteApi_sim_handle_parent
#define remoteApi_sim_handle_parent -11L
#undef remoteApi_sim_distcalcmethod_dl
#define remoteApi_sim_distcalcmethod_dl 0L
#undef remoteApi_sim_distcalcmethod_dac
#define remoteApi_sim_distcalcmethod_dac 1L
#undef remoteApi_sim_distcalcmethod_max_dl_dac
#define remoteApi_sim_distcalcmethod_max_dl_dac 2L
#undef remoteApi_sim_distcalcmethod_dl_and_dac
#define remoteApi_sim_distcalcmethod_dl_and_dac 3L
#undef remoteApi_sim_distcalcmethod_sqrt_dl2_and_dac2
#define remoteApi_sim_distcalcmethod_sqrt_dl2_and_dac2 4L
#undef remoteApi_sim_distcalcmethod_dl_if_nonzero
#define remoteApi_sim_distcalcmethod_dl_if_nonzero 5L
#undef remoteApi_sim_distcalcmethod_dac_if_nonzero
#define remoteApi_sim_distcalcmethod_dac_if_nonzero 6L
#undef remoteApi_sim_dlgstyle_message
#define remoteApi_sim_dlgstyle_message 0L
#undef remoteApi_sim_dlgstyle_input
#define remoteApi_sim_dlgstyle_input 1L
#undef remoteApi_sim_dlgstyle_ok
#define remoteApi_sim_dlgstyle_ok 2L
#undef remoteApi_sim_dlgstyle_ok_cancel
#define remoteApi_sim_dlgstyle_ok_cancel 3L
#undef remoteApi_sim_dlgstyle_yes_no
#define remoteApi_sim_dlgstyle_yes_no 4L
#undef remoteApi_sim_dlgstyle_dont_center
#define remoteApi_sim_dlgstyle_dont_center 32L
#undef remoteApi_sim_dlgret_still_open
#define remoteApi_sim_dlgret_still_open 0L
#undef remoteApi_sim_dlgret_ok
#define remoteApi_sim_dlgret_ok 1L
#undef remoteApi_sim_dlgret_cancel
#define remoteApi_sim_dlgret_cancel 2L
#undef remoteApi_sim_dlgret_yes
#define remoteApi_sim_dlgret_yes 3L
#undef remoteApi_sim_dlgret_no
#define remoteApi_sim_dlgret_no 4L
#undef remoteApi_sim_pathproperty_show_line
#define remoteApi_sim_pathproperty_show_line 1L
#undef remoteApi_sim_pathproperty_show_orientation
#define remoteApi_sim_pathproperty_show_orientation 2L
#undef remoteApi_sim_pathproperty_closed_path
#define remoteApi_sim_pathproperty_closed_path 4L
#undef remoteApi_sim_pathproperty_automatic_orientation
#define remoteApi_sim_pathproperty_automatic_orientation 8L
#undef remoteApi_sim_pathproperty_invert_velocity
#define remoteApi_sim_pathproperty_invert_velocity 16L
#undef remoteApi_sim_pathproperty_infinite_acceleration
#define remoteApi_sim_pathproperty_infinite_acceleration 32L
#undef remoteApi_sim_pathproperty_flat_path
#define remoteApi_sim_pathproperty_flat_path 64L
#undef remoteApi_sim_pathproperty_show_position
#define remoteApi_sim_pathproperty_show_position 128L
#undef remoteApi_sim_pathproperty_auto_velocity_profile_translation
#define remoteApi_sim_pathproperty_auto_velocity_profile_translation 256L
#undef remoteApi_sim_pathproperty_auto_velocity_profile_rotation
#define remoteApi_sim_pathproperty_auto_velocity_profile_rotation 512L
#undef remoteApi_sim_pathproperty_endpoints_at_zero
#define remoteApi_sim_pathproperty_endpoints_at_zero 1024L
#undef remoteApi_sim_pathproperty_keep_x_up
#define remoteApi_sim_pathproperty_keep_x_up 2048L
#undef remoteApi_sim_drawing_points
#define remoteApi_sim_drawing_points 0L
#undef remoteApi_sim_drawing_lines
#define remoteApi_sim_drawing_lines 1L
#undef remoteApi_sim_drawing_triangles
#define remoteApi_sim_drawing_triangles 2L
#undef remoteApi_sim_drawing_trianglepoints
#define remoteApi_sim_drawing_trianglepoints 3L
#undef remoteApi_sim_drawing_quadpoints
#define remoteApi_sim_drawing_quadpoints 4L
#undef remoteApi_sim_drawing_discpoints
#define remoteApi_sim_drawing_discpoints 5L
#undef remoteApi_sim_drawing_cubepoints
#define remoteApi_sim_drawing_cubepoints 6L
#undef remoteApi_sim_drawing_spherepoints
#define remoteApi_sim_drawing_spherepoints 7L
#undef remoteApi_sim_drawing_itemcolors
#define remoteApi_sim_drawing_itemcolors 32L
#undef remoteApi_sim_drawing_vertexcolors
#define remoteApi_sim_drawing_vertexcolors 64L
#undef remoteApi_sim_drawing_itemsizes
#define remoteApi_sim_drawing_itemsizes 128L
#undef remoteApi_sim_drawing_backfaceculling
#define remoteApi_sim_drawing_backfaceculling 256L
#undef remoteApi_sim_drawing_wireframe
#define remoteApi_sim_drawing_wireframe 512L
#undef remoteApi_sim_drawing_painttag
#define remoteApi_sim_drawing_painttag 1024L
#undef remoteApi_sim_drawing_followparentvisibility
#define remoteApi_sim_drawing_followparentvisibility 2048L
#undef remoteApi_sim_drawing_cyclic
#define remoteApi_sim_drawing_cyclic 4096L
#undef remoteApi_sim_drawing_50percenttransparency
#define remoteApi_sim_drawing_50percenttransparency 8492L
#undef remoteApi_sim_drawing_25percenttransparency
#define remoteApi_sim_drawing_25percenttransparency 16384L
#undef remoteApi_sim_drawing_12percenttransparency
#define remoteApi_sim_drawing_12percenttransparency 32768L
#undef remoteApi_sim_drawing_emissioncolor
#define remoteApi_sim_drawing_emissioncolor 65536L
#undef remoteApi_sim_drawing_facingcamera
#define remoteApi_sim_drawing_facingcamera 131072L
#undef remoteApi_sim_drawing_overlay
#define remoteApi_sim_drawing_overlay 262144L
#undef remoteApi_sim_drawing_itemtransparency
#define remoteApi_sim_drawing_itemtransparency 524288L
#undef remoteApi_sim_banner_left
#define remoteApi_sim_banner_left 1L
#undef remoteApi_sim_banner_right
#define remoteApi_sim_banner_right 2L
#undef remoteApi_sim_banner_nobackground
#define remoteApi_sim_banner_nobackground 4L
#undef remoteApi_sim_banner_overlay
#define remoteApi_sim_banner_overlay 8L
#undef remoteApi_sim_banner_followparentvisibility
#define remoteApi_sim_banner_followparentvisibility 16L
#undef remoteApi_sim_banner_clickselectsparent
#define remoteApi_sim_banner_clickselectsparent 32L
#undef remoteApi_sim_banner_clicktriggersevent
#define remoteApi_sim_banner_clicktriggersevent 64L
#undef remoteApi_sim_banner_facingcamera
#define remoteApi_sim_banner_facingcamera 128L
#undef remoteApi_sim_banner_fullyfacingcamera
#define remoteApi_sim_banner_fullyfacingcamera 256L
#undef remoteApi_sim_banner_backfaceculling
#define remoteApi_sim_banner_backfaceculling 512L
#undef remoteApi_sim_banner_keepsamesize
#define remoteApi_sim_banner_keepsamesize 1024L
#undef remoteApi_sim_banner_bitmapfont
#define remoteApi_sim_banner_bitmapfont 2048L
#undef remoteApi_sim_particle_points1
#define remoteApi_sim_particle_points1 0L
#undef remoteApi_sim_particle_points2
#define remoteApi_sim_particle_points2 1L
#undef remoteApi_sim_particle_points4
#define remoteApi_sim_particle_points4 2L
#undef remoteApi_sim_particle_roughspheres
#define remoteApi_sim_particle_roughspheres 3L
#undef remoteApi_sim_particle_spheres
#define remoteApi_sim_particle_spheres 4L
#undef remoteApi_sim_particle_respondable1to4
#define remoteApi_sim_particle_respondable1to4 32L
#undef remoteApi_sim_particle_respondable5to8
#define remoteApi_sim_particle_respondable5to8 64L
#undef remoteApi_sim_particle_particlerespondable
#define remoteApi_sim_particle_particlerespondable 128L
#undef remoteApi_sim_particle_ignoresgravity
#define remoteApi_sim_particle_ignoresgravity 256L
#undef remoteApi_sim_particle_invisible
#define remoteApi_sim_particle_invisible 512L
#undef remoteApi_sim_particle_itemsizes
#define remoteApi_sim_particle_itemsizes 1024L
#undef remoteApi_sim_particle_itemdensities
#define remoteApi_sim_particle_itemdensities 2048L
#undef remoteApi_sim_particle_itemcolors
#define remoteApi_sim_particle_itemcolors 4096L
#undef remoteApi_sim_particle_cyclic
#define remoteApi_sim_particle_cyclic 8192L
#undef remoteApi_sim_particle_emissioncolor
#define remoteApi_sim_particle_emissioncolor 16384L
#undef remoteApi_sim_particle_water
#define remoteApi_sim_particle_water 32768L
#undef remoteApi_sim_particle_painttag
#define remoteApi_sim_particle_painttag 65536L
#undef remoteApi_sim_ui_menu_title
#define remoteApi_sim_ui_menu_title 1L
#undef remoteApi_sim_ui_menu_minimize
#define remoteApi_sim_ui_menu_minimize 2L
#undef remoteApi_sim_ui_menu_close
#define remoteApi_sim_ui_menu_close 4L
#undef remoteApi_sim_ui_menu_systemblock
#define remoteApi_sim_ui_menu_systemblock 8L
#undef remoteApi_sim_boolparam_hierarchy_visible
#define remoteApi_sim_boolparam_hierarchy_visible 0L
#undef remoteApi_sim_boolparam_console_visible
#define remoteApi_sim_boolparam_console_visible 1L
#undef remoteApi_sim_boolparam_collision_handling_enabled
#define remoteApi_sim_boolparam_collision_handling_enabled 2L
#undef remoteApi_sim_boolparam_distance_handling_enabled
#define remoteApi_sim_boolparam_distance_handling_enabled 3L
#undef remoteApi_sim_boolparam_ik_handling_enabled
#define remoteApi_sim_boolparam_ik_handling_enabled 4L
#undef remoteApi_sim_boolparam_gcs_handling_enabled
#define remoteApi_sim_boolparam_gcs_handling_enabled 5L
#undef remoteApi_sim_boolparam_dynamics_handling_enabled
#define remoteApi_sim_boolparam_dynamics_handling_enabled 6L
#undef remoteApi_sim_boolparam_joint_motion_handling_enabled
#define remoteApi_sim_boolparam_joint_motion_handling_enabled 7L
#undef remoteApi_sim_boolparam_path_motion_handling_enabled
#define remoteApi_sim_boolparam_path_motion_handling_enabled 8L
#undef remoteApi_sim_boolparam_proximity_sensor_handling_enabled
#define remoteApi_sim_boolparam_proximity_sensor_handling_enabled 9L
#undef remoteApi_sim_boolparam_vision_sensor_handling_enabled
#define remoteApi_sim_boolparam_vision_sensor_handling_enabled 10L
#undef remoteApi_sim_boolparam_mill_handling_enabled
#define remoteApi_sim_boolparam_mill_handling_enabled 11L
#undef remoteApi_sim_boolparam_browser_visible
#define remoteApi_sim_boolparam_browser_visible 12L
#undef remoteApi_sim_boolparam_scene_and_model_load_messages
#define remoteApi_sim_boolparam_scene_and_model_load_messages 13L
#undef remoteApi_sim_reserved0
#define remoteApi_sim_reserved0 14L
#undef remoteApi_sim_boolparam_shape_textures_are_visible
#define remoteApi_sim_boolparam_shape_textures_are_visible 15L
#undef remoteApi_sim_boolparam_display_enabled
#define remoteApi_sim_boolparam_display_enabled 16L
#undef remoteApi_sim_boolparam_infotext_visible
#define remoteApi_sim_boolparam_infotext_visible 17L
#undef remoteApi_sim_boolparam_statustext_open
#define remoteApi_sim_boolparam_statustext_open 18L
#undef remoteApi_sim_boolparam_fog_enabled
#define remoteApi_sim_boolparam_fog_enabled 19L
#undef remoteApi_sim_boolparam_rml2_available
#define remoteApi_sim_boolparam_rml2_available 20L
#undef remoteApi_sim_boolparam_rml4_available
#define remoteApi_sim_boolparam_rml4_available 21L
#undef remoteApi_sim_boolparam_mirrors_enabled
#define remoteApi_sim_boolparam_mirrors_enabled 22L
#undef remoteApi_sim_boolparam_aux_clip_planes_enabled
#define remoteApi_sim_boolparam_aux_clip_planes_enabled 23L
#undef remoteApi_sim_boolparam_full_model_copy_from_api
#define remoteApi_sim_boolparam_full_model_copy_from_api 24L
#undef remoteApi_sim_boolparam_realtime_simulation
#define remoteApi_sim_boolparam_realtime_simulation 25L
#undef remoteApi_sim_intparam_error_report_mode
#define remoteApi_sim_intparam_error_report_mode 0L
#undef remoteApi_sim_intparam_program_version
#define remoteApi_sim_intparam_program_version 1L
#undef remoteApi_sim_intparam_instance_count
#define remoteApi_sim_intparam_instance_count 2L
#undef remoteApi_sim_intparam_custom_cmd_start_id
#define remoteApi_sim_intparam_custom_cmd_start_id 3L
#undef remoteApi_sim_intparam_compilation_version
#define remoteApi_sim_intparam_compilation_version 4L
#undef remoteApi_sim_intparam_current_page
#define remoteApi_sim_intparam_current_page 5L
#undef remoteApi_sim_intparam_flymode_camera_handle
#define remoteApi_sim_intparam_flymode_camera_handle 6L
#undef remoteApi_sim_intparam_dynamic_step_divider
#define remoteApi_sim_intparam_dynamic_step_divider 7L
#undef remoteApi_sim_intparam_dynamic_engine
#define remoteApi_sim_intparam_dynamic_engine 8L
#undef remoteApi_sim_intparam_server_port_start
#define remoteApi_sim_intparam_server_port_start 9L
#undef remoteApi_sim_intparam_server_port_range
#define remoteApi_sim_intparam_server_port_range 10L
#undef remoteApi_sim_intparam_visible_layers
#define remoteApi_sim_intparam_visible_layers 11L
#undef remoteApi_sim_intparam_infotext_style
#define remoteApi_sim_intparam_infotext_style 12L
#undef remoteApi_sim_intparam_settings
#define remoteApi_sim_intparam_settings 13L
#undef remoteApi_sim_intparam_edit_mode_type
#define remoteApi_sim_intparam_edit_mode_type 14L
#undef remoteApi_sim_intparam_server_port_next
#define remoteApi_sim_intparam_server_port_next 15L
#undef remoteApi_sim_intparam_qt_version
#define remoteApi_sim_intparam_qt_version 16L
#undef remoteApi_sim_intparam_event_flags_read
#define remoteApi_sim_intparam_event_flags_read 17L
#undef remoteApi_sim_intparam_event_flags_read_clear
#define remoteApi_sim_intparam_event_flags_read_clear 18L
#undef remoteApi_sim_intparam_platform
#define remoteApi_sim_intparam_platform 19L
#undef remoteApi_sim_intparam_scene_unique_id
#define remoteApi_sim_intparam_scene_unique_id 20L
#undef remoteApi_sim_floatparam_rand
#define remoteApi_sim_floatparam_rand 0L
#undef remoteApi_sim_floatparam_simulation_time_step
#define remoteApi_sim_floatparam_simulation_time_step 1L
#undef remoteApi_sim_stringparam_application_path
#define remoteApi_sim_stringparam_application_path 0L
#undef remoteApi_sim_arrayparam_gravity
#define remoteApi_sim_arrayparam_gravity 0L
#undef remoteApi_sim_arrayparam_fog
#define remoteApi_sim_arrayparam_fog 1L
#undef remoteApi_sim_arrayparam_fog_color
#define remoteApi_sim_arrayparam_fog_color 2L
#undef remoteApi_sim_arrayparam_background_color1
#define remoteApi_sim_arrayparam_background_color1 3L
#undef remoteApi_sim_arrayparam_background_color2
#define remoteApi_sim_arrayparam_background_color2 4L
#undef remoteApi_sim_arrayparam_ambient_light
#define remoteApi_sim_arrayparam_ambient_light 5L
#undef remoteApi_sim_gui_menubar
#define remoteApi_sim_gui_menubar 1L
#undef remoteApi_sim_gui_popups
#define remoteApi_sim_gui_popups 2L
#undef remoteApi_sim_gui_toolbar1
#define remoteApi_sim_gui_toolbar1 4L
#undef remoteApi_sim_gui_toolbar2
#define remoteApi_sim_gui_toolbar2 8L
#undef remoteApi_sim_gui_hierarchy
#define remoteApi_sim_gui_hierarchy 16L
#undef remoteApi_sim_gui_infobar
#define remoteApi_sim_gui_infobar 32L
#undef remoteApi_sim_gui_statusbar
#define remoteApi_sim_gui_statusbar 64L
#undef remoteApi_sim_gui_scripteditor
#define remoteApi_sim_gui_scripteditor 128L
#undef remoteApi_sim_gui_scriptsimulationparameters
#define remoteApi_sim_gui_scriptsimulationparameters 256L
#undef remoteApi_sim_gui_dialogs
#define remoteApi_sim_gui_dialogs 512L
#undef remoteApi_sim_gui_browser
#define remoteApi_sim_gui_browser 1024L
#undef remoteApi_sim_gui_all
#define remoteApi_sim_gui_all 65535L
#undef remoteApi_sim_jointmode_passive
#define remoteApi_sim_jointmode_passive 0L
#undef remoteApi_sim_jointmode_motion
#define remoteApi_sim_jointmode_motion 1L
#undef remoteApi_sim_jointmode_ik
#define remoteApi_sim_jointmode_ik 2L
#undef remoteApi_sim_jointmode_ikdependent
#define remoteApi_sim_jointmode_ikdependent 3L
#undef remoteApi_sim_jointmode_dependent
#define remoteApi_sim_jointmode_dependent 4L
#undef remoteApi_sim_jointmode_force
#define remoteApi_sim_jointmode_force 5L
#undef remoteApi_sim_navigation_passive
#define remoteApi_sim_navigation_passive 0L
#undef remoteApi_sim_navigation_camerashift
#define remoteApi_sim_navigation_camerashift 1L
#undef remoteApi_sim_navigation_camerarotate
#define remoteApi_sim_navigation_camerarotate 2L
#undef remoteApi_sim_navigation_camerazoom
#define remoteApi_sim_navigation_camerazoom 3L
#undef remoteApi_sim_navigation_cameratilt
#define remoteApi_sim_navigation_cameratilt 4L
#undef remoteApi_sim_navigation_cameraangle
#define remoteApi_sim_navigation_cameraangle 5L
#undef remoteApi_sim_navigation_camerafly
#define remoteApi_sim_navigation_camerafly 6L
#undef remoteApi_sim_navigation_objectshift
#define remoteApi_sim_navigation_objectshift 7L
#undef remoteApi_sim_navigation_objectrotate
#define remoteApi_sim_navigation_objectrotate 8L
#undef remoteApi_sim_navigation_reserved2
#define remoteApi_sim_navigation_reserved2 9L
#undef remoteApi_sim_navigation_reserved3
#define remoteApi_sim_navigation_reserved3 10L
#undef remoteApi_sim_navigation_jointpathtest
#define remoteApi_sim_navigation_jointpathtest 11L
#undef remoteApi_sim_navigation_ikmanip
#define remoteApi_sim_navigation_ikmanip 12L
#undef remoteApi_sim_navigation_objectmultipleselection
#define remoteApi_sim_navigation_objectmultipleselection 13L
#undef remoteApi_sim_navigation_reserved4
#define remoteApi_sim_navigation_reserved4 256L
#undef remoteApi_sim_navigation_clickselection
#define remoteApi_sim_navigation_clickselection 512L
#undef remoteApi_sim_navigation_ctrlselection
#define remoteApi_sim_navigation_ctrlselection 1024L
#undef remoteApi_sim_navigation_shiftselection
#define remoteApi_sim_navigation_shiftselection 2048L
#undef remoteApi_sim_navigation_camerazoomwheel
#define remoteApi_sim_navigation_camerazoomwheel 4096L
#undef remoteApi_sim_navigation_camerarotaterightbutton
#define remoteApi_sim_navigation_camerarotaterightbutton 8192L
#undef remoteApi_simx_error_noerror
#define remoteApi_simx_error_noerror 0L
#undef remoteApi_simx_error_novalue_flag
#define remoteApi_simx_error_novalue_flag 1L
#undef remoteApi_simx_error_timeout_flag
#define remoteApi_simx_error_timeout_flag 2L
#undef remoteApi_simx_error_illegal_opmode_flag
#define remoteApi_simx_error_illegal_opmode_flag 4L
#undef remoteApi_simx_error_remote_error_flag
#define remoteApi_simx_error_remote_error_flag 8L
#undef remoteApi_simx_error_split_progress_flag
#define remoteApi_simx_error_split_progress_flag 16L
#undef remoteApi_simx_error_local_error_flag
#define remoteApi_simx_error_local_error_flag 32L
#undef remoteApi_simx_error_initialize_error_flag
#define remoteApi_simx_error_initialize_error_flag 64L

#undef remoteApi_simx_opmode_oneshot
#define remoteApi_simx_opmode_oneshot 0L
#undef remoteApi_simx_opmode_oneshot_wait
#define remoteApi_simx_opmode_oneshot_wait 65536L
#undef remoteApi_simx_opmode_streaming
#define remoteApi_simx_opmode_streaming 131072L
#undef remoteApi_simx_opmode_continuous
#define remoteApi_simx_opmode_continuous 131072L
#undef remoteApi_simx_opmode_oneshot_split
#define remoteApi_simx_opmode_oneshot_split 196608L
#undef remoteApi_simx_opmode_continuous_split
#define remoteApi_simx_opmode_continuous_split 262144L
#undef remoteApi_simx_opmode_streaming_split
#define remoteApi_simx_opmode_streaming_split 262144L
#undef remoteApi_simx_opmode_discontinue
#define remoteApi_simx_opmode_discontinue 327680L
#undef remoteApi_simx_opmode_buffer
#define remoteApi_simx_opmode_buffer 393216L
#undef remoteApi_simx_opmode_remove
#define remoteApi_simx_opmode_remove 458752L
/*
 * Class:     remoteApi
 * Method:    test
 * Signature: (LStringWA;LStringW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_test
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxStart
 * Signature: (Ljava/lang/String;IZZ)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxStart
  (JNIEnv *, jobject, jstring, jint, jboolean, jboolean, jint);

/*
 * Class:     remoteApi
 * Method:    simxFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_remoteApi_simxFinish
  (JNIEnv *, jobject);

/*
 * Class:     remoteApi
 * Method:    simxGetConnectionId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetConnectionId
  (JNIEnv *, jobject);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectHandle
 * Signature: (Ljava/lang/String;LIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectHandle
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetJointPosition
 * Signature: (ILFloatW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetJointPosition
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetJointPosition
 * Signature: (IFI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetJointPosition
  (JNIEnv *, jobject, jint, jfloat, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectPosition
 * Signature: (IILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectPosition
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetObjectPosition
 * Signature: (IILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetObjectPosition
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetVisionSensorImage
 * Signature: (ILIntWA;LCharWA;II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetVisionSensorImage
  (JNIEnv *, jobject, jint, jobject, jobject, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetVisionSensorImage
 * Signature: (ILCharWA;III)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetVisionSensorImage
  (JNIEnv *, jobject, jint, jobject, jint, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetJointMatrix
 * Signature: (ILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetJointMatrix
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetSphericalJointMatrix
 * Signature: (ILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetSphericalJointMatrix
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetJointTargetVelocity
 * Signature: (IFI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetJointTargetVelocity
  (JNIEnv *, jobject, jint, jfloat, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetJointTargetPosition
 * Signature: (IFI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetJointTargetPosition
  (JNIEnv *, jobject, jint, jfloat, jint);

/*
 * Class:     remoteApi
 * Method:    simxJointGetForce
 * Signature: (ILFloatW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxJointGetForce
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetJointForce
 * Signature: (IFI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetJointForce
  (JNIEnv *, jobject, jint, jfloat, jint);

/*
 * Class:     remoteApi
 * Method:    simxReadForceSensor
 * Signature: (ILIntW;LFloatWA;LFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxReadForceSensor
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxBreakForceSensor
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxBreakForceSensor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxReadVisionSensor
 * Signature: (ILBoolW;LFloatWAA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxReadVisionSensor
  (JNIEnv *, jobject, jint, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectFloatParameter
 * Signature: (IILFloatW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectFloatParameter
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetObjectFloatParameter
 * Signature: (IIFI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetObjectFloatParameter
  (JNIEnv *, jobject, jint, jint, jfloat, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectIntParameter
 * Signature: (IILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectIntParameter
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetObjectIntParameter
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetObjectIntParameter
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetModelProperty
 * Signature: (ILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetModelProperty
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetModelProperty
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetModelProperty
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetVisionSensorDepthBuffer
 * Signature: (ILIntWA;LFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetVisionSensorDepthBuffer
  (JNIEnv *, jobject, jint, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectChild
 * Signature: (IILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectChild
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectParent
 * Signature: (ILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectParent
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxStartSimulation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxStartSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxPauseSimulation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxPauseSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxStopSimulation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxStopSimulation
  (JNIEnv *, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetUISlider
 * Signature: (IILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetUISlider
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetUISlider
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetUISlider
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetUIEventButton
 * Signature: (ILIntW;LIntWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetUIEventButton
  (JNIEnv *, jobject, jint, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetUIButtonProperty
 * Signature: (IILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetUIButtonProperty
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetUIButtonProperty
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetUIButtonProperty
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxAuxiliaryConsoleClose
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxAuxiliaryConsoleClose
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxAuxiliaryConsoleShow
 * Signature: (IZI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxAuxiliaryConsoleShow
  (JNIEnv *, jobject, jint, jboolean, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectOrientation
 * Signature: (IILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectOrientation
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetObjectParent
 * Signature: (IIZI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetObjectParent
  (JNIEnv *, jobject, jint, jint, jboolean, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetArrayParameter
 * Signature: (ILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetArrayParameter
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetArrayParameter
 * Signature: (ILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetArrayParameter
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetIntegerParameter
 * Signature: (ILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetIntegerParameter
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetIntegerParameter
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetIntegerParameter
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetBooleanParameter
 * Signature: (ILBoolW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetBooleanParameter
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetDialogResult
 * Signature: (ILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetDialogResult
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetFloatingParameter
 * Signature: (IFI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetFloatingParameter
  (JNIEnv *, jobject, jint, jfloat, jint);

/*
 * Class:     remoteApi
 * Method:    simxRemoveObject
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxRemoveObject
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxRemoveUI
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxRemoveUI
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxCloseScene
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxCloseScene
  (JNIEnv *, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxEndDialog
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxEndDialog
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxReadDistance
 * Signature: (ILFloatW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxReadDistance
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetFloatingParameter
 * Signature: (ILFloatW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetFloatingParameter
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetObjectOrientation
 * Signature: (IILFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetObjectOrientation
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxReadProximitySensor
 * Signature: (ILBoolW;LFloatWA;LIntW;LFloatWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxReadProximitySensor
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxLoadModel
 * Signature: (Ljava/lang/String;ILIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxLoadModel
  (JNIEnv *, jobject, jstring, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxLoadUI
 * Signature: (Ljava/lang/String;ILIntWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxLoadUI
  (JNIEnv *, jobject, jstring, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxLoadScene
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxLoadScene
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetUIHandle
 * Signature: (Ljava/lang/String;LIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetUIHandle
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxAddStatusbarMessage
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxAddStatusbarMessage
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     remoteApi
 * Method:    simxAuxiliaryConsoleOpen
 * Signature: (Ljava/lang/String;IILIntWA;LIntWA;LFloatWA;LFloatWA;LIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxAuxiliaryConsoleOpen
  (JNIEnv *, jobject, jstring, jint, jint, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxAuxiliaryConsolePrint
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxAuxiliaryConsolePrint
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetUIButtonLabel
 * Signature: (IILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetUIButtonLabel
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetLastErrors
 * Signature: (LStringWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetLastErrors
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetBooleanParameter
 * Signature: (IZI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetBooleanParameter
  (JNIEnv *, jobject, jint, jboolean, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetStringParameter
 * Signature: (ILStringW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetStringParameter
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetCollisionHandle
 * Signature: (Ljava/lang/String;LIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetCollisionHandle
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetDistanceHandle
 * Signature: (Ljava/lang/String;LIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetDistanceHandle
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxReadCollision
 * Signature: (ILBoolW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxReadCollision
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjects
 * Signature: (ILIntWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjects
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxDisplayDialog
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;LFloatWA;LFloatWA;LIntW;LIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxDisplayDialog
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetDialogInput
 * Signature: (ILStringW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetDialogInput
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxCopyPasteObjects
 * Signature: (LIntWA;LIntWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxCopyPasteObjects
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetObjectSelection
 * Signature: (LIntWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetObjectSelection
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetObjectSelection
 * Signature: (LIntWA;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetObjectSelection
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxClearFloatSignal
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxClearFloatSignal
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     remoteApi
 * Method:    simxClearStringSignal
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxClearStringSignal
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     remoteApi
 * Method:    simxClearIntegerSignal
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxClearIntegerSignal
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetFloatSignal
 * Signature: (Ljava/lang/String;LFloatW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetFloatSignal
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetIntegerSignal
 * Signature: (Ljava/lang/String;LIntW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetIntegerSignal
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetStringSignal
 * Signature: (Ljava/lang/String;LStringW;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetStringSignal
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetFloatSignal
 * Signature: (Ljava/lang/String;FI)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetFloatSignal
  (JNIEnv *, jobject, jstring, jfloat, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetIntegerSignal
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetIntegerSignal
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxSetStringSignal
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSetStringSignal
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     remoteApi
 * Method:    simxGetPingTime
 * Signature: (LIntW;)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetPingTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     remoteApi
 * Method:    simxGetLastCmdTime
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetLastCmdTime
  (JNIEnv *, jobject);

/*
 * Class:     remoteApi
 * Method:    simxSynchronousTrigger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSynchronousTrigger
  (JNIEnv *, jobject);

/*
 * Class:     remoteApi
 * Method:    simxSynchronous
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxSynchronous
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     remoteApi
 * Method:    simxPauseCommunication
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxPauseCommunication
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     remoteApi
 * Method:    simxGetInMessageInfo
 * Signature: (ILIntW;)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetInMessageInfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     remoteApi
 * Method:    simxGetOutMessageInfo
 * Signature: (ILIntW;)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxGetOutMessageInfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     remoteApi
 * Method:    simxTransferFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxTransferFile
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     remoteApi
 * Method:    simxEraseFile
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_remoteApi_simxEraseFile
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
